package:
  name: xray-vision
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: ../


build:
  number: 0
  string: {{ environ.get('GIT_BUILD_STR', '') }}_np{{ np }}py{{ py }}

requirements:
  build:
    - python
    - distribute
    - numpy
    - six
    - matplotlib
  run:
    - python
    - numpy
    - matplotlib
    - pyqt
    - six

test:
  requires:
    - nose

  imports:
    - xray_vision
    - xray_vision.qt_widgets
    - xray_vision.messenger
    - xray_vision.messenger.mpl
    - xray_vision.backend
    - xray_vision.backend.mpl


about:
  home: https://github.com/Nikea/xray-vision
  license: 3-Clause BSD
